### ISSUE TITLE
fix theme to show sidebar buttons on mobile

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/awaitlet#5]

**Comment by zzzeek** [comment]
I think perhaps the CSS changes should be moved from the alembic/dogpile/awaitlet repos and into build_ln where they're all in one place.  we have css overrrides there also

**Comment by zzzeek** [comment]
ive removed the override from all three projects and it was already locally in my build_ln script, will get it onto the server then you can show me how to set it for mobile only

**Comment by CaselIT** [comment]
I see. I've opened this issue just as reminder.
How to do this on mobile only are something like `@media only screen and (min-width: xyzpx) {`

Looking at the theme behaviour it seems that at 960px it collapses the left side sidebar

so something like this I think
```css
@media only screen and (min-width: 960px) {
  .sidebar-toggle.primary-toggle {
    display: !important;
  }
}
```
(I've added `primary-toggle` otherwise it applies also to the right side sidebar)
